name: pattern-recognition
channels:
  - defaults
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python
  - pytorch
  - cpuonly
  - pyg
  - optuna
  - numpy
  - ipython
  - jupyterlab
  - jupyter
  - ipywidgets
  - python-lsp-server
  - scikit-posthocs
  - lightning
  - torchmetrics

