name: pattern-recognition
channels:
  - defaults
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python < 3.12
  - pytorch
  - cpuonly
  - pyg
  - optuna
  - numpy < 2
  - ipython
  - jupyterlab
  - jupyter
  - ipywidgets
  - python-lsp-server

