# Default configuration for the GNN experiments

[io]
root = "Processed Data"
raw_data_dir = "Data"
train_file = "GridData_DS4_all_data.processed"
test_file = "GridData_DS3_all_data.processed"
val_file = ""
studies_dir = "optuna_studies"
state_dict_dir = "results/state_dicts"
stats_results_file = "results/statistical_results.parquet"
cross_eval_results_file = "results/cross_dataset_evaluation.parquet"
output_dir = "results/analysis_plots"
log_dir = "lightning_logs"

[model]
label = "average_firing_rates"
prediction_level = "node"
gnn_operator = ["cheb", "gcn", "sgc", "tag", "ssg"]

[training]
num_runs = 30
num_workers = 8
max_epochs = 100
patience = 5
val_split = 0.3

[optimization]
n_trials = 100
timeout = 3600

[hetero_model]
gnn_operator = "rgat"

[hetero_training]
max_epochs = 100
patience = 10
num_workers = 3

[hetero_optimization]
all_operators = false
n_trials = 100
timeout = 7200
study_name = "hetero_gnn_spn_optimization"

[cross_validation]
datasets = [
    "GridData_DS1_all_data.processed",
    "GridData_DS2_all_data.processed",
    "GridData_DS5_all_data.processed",
    "RandData_DS1_train_data.processed",
    "RandData_DS2_train_data.processed",
]

[analysis]
main_metrics = ["test/rmse", "test/mae", "test/mape", "val/rmse"]
cross_val_metrics = ["test/rmse", "test/mae", "test/mape"]
generate_critical_diagram = true
generate_performance_complexity_plot = true
generate_cross_eval_heatmap = true
